version: '3'
services:
  node:
    build: .
    container_name: react-app_fukusyu
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd react-sample && yarn install && yarn start"
    ports:
      - "4900:3000"